spring:
  datasource:
    url: jdbc:mysql://localhost:3307/accountantdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sendgrid:
    api-key: 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

jwt:
  secret: 3Fj8pD6xRv9nT6yUz4wA9hXrQ2bK7jL5
stripe:
  api:
    key: sk_test_51QBLeXFWqYIjorXP4sqcGat06jMBUs3IuTtSuWQOtMTLQTPHjLtdhQcu6ii7AvPtiKxKAcnIUGW0GkaWghSJfP33009K3lbRej
  webhook:
    secret: whsec_5b13680d1f948109c7d4daa7b8b9764e06c9314f4d1922358871f67d463f64c9
  unparalleled:
    priceId: prod_R8bMstAdzJeoMA
  one-time:
    Pro: prod_R8bQvxPWyE69qY
    Premium: prod_R8bPVqfuvk6ze3
    Business: prod_R8bOFEUXlM4BM5
    Enterprise: prod_R8bO4Izu7lHj84
google:
  credentials:
    path: backend/src/main/resources/macro-context-416213-59760d902b8a.json
  application:
    name: Unparallaled-Invoices
  folder:
    id: 1xJ9gPWsnrlS7zkEKFrPKTBq_0JLVwr70